//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wnct2.Models.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quanao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quanao()
        {
            this.CTHoaDon = new HashSet<CTHoaDon>();
        }
    
        public string Mahh { get; set; }
        public string Tenhh { get; set; }
        public Nullable<int> DongGia { get; set; }
        public string Producer { get; set; }
        public Nullable<System.DateTime> Hsd { get; set; }
        public string Anh { get; set; }
        public string Type { get; set; }
        public string Mota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDon { get; set; }
    }
}
